/*
 * MTC-CA Admin API
 *
 * Administrative HTTP+JSON API for the Merkle Tree Certificate CA (spec §17.2). Consumed by `mtcctl` (via the generated Rust client) and the admin UI. Seed surface: health endpoints (§20.5) and a minimal service status endpoint (§17.3).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CheckpointStatus : Latest signed checkpoint summary (spec §8, §17.3).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckpointStatus {
    /// Number of leaves in the log at this checkpoint.
    #[serde(rename = "tree_size")]
    pub tree_size: i64,
    /// Hex-encoded Merkle tree root hash.
    #[serde(rename = "root_hash")]
    pub root_hash: String,
    /// Checkpoint signing time (RFC 3339).
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl CheckpointStatus {
    /// Latest signed checkpoint summary (spec §8, §17.3).
    pub fn new(
        tree_size: i64,
        root_hash: String,
        timestamp: chrono::DateTime<chrono::FixedOffset>,
    ) -> CheckpointStatus {
        CheckpointStatus {
            tree_size,
            root_hash,
            timestamp,
        }
    }
}
