/*
 * MTC-CA Admin API
 *
 * Administrative HTTP+JSON API for the Merkle Tree Certificate CA (spec §17.2). Consumed by `mtcctl` (via the generated Rust client) and the admin UI. Seed surface: health endpoints (§20.5) and a minimal service status endpoint (§17.3).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LeaseStatus : Current write-lease state (spec §8, §17.3).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeaseStatus {
    /// Region currently holding the write lease.
    #[serde(rename = "holder")]
    pub holder: String,
    /// Current lease epoch.
    #[serde(rename = "epoch")]
    pub epoch: i64,
    /// Lease expiry time (RFC 3339).
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
}

impl LeaseStatus {
    /// Current write-lease state (spec §8, §17.3).
    pub fn new(
        holder: String,
        epoch: i64,
        expires_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> LeaseStatus {
        LeaseStatus {
            holder,
            epoch,
            expires_at,
        }
    }
}
