/*
 * MTC-CA Admin API
 *
 * Administrative HTTP+JSON API for the Merkle Tree Certificate CA (spec §17.2). Consumed by `mtcctl` (via the generated Rust client) and the admin UI. Seed surface: health endpoints (§20.5) and a minimal service status endpoint (§17.3).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusResponse : Minimal service status (spec §17.3).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "service")]
    pub service: models::ServiceInfo,
    #[serde(rename = "lease", skip_serializing_if = "Option::is_none")]
    pub lease: Option<models::LeaseStatus>,
    #[serde(rename = "checkpoint", skip_serializing_if = "Option::is_none")]
    pub checkpoint: Option<models::CheckpointStatus>,
}

impl StatusResponse {
    /// Minimal service status (spec §17.3).
    pub fn new(service: models::ServiceInfo) -> StatusResponse {
        StatusResponse {
            service,
            lease: None,
            checkpoint: None,
        }
    }
}
