//! Spec conformance test-vector loader and runner (testing-infra epic,
//! ticket `test-conformance-runner`; spec §19.4, roadmap Phase 1 "Spec
//! conformance suite scaffolding").
//!
//! This crate is the harness, not the vectors: it defines the JSON+hex
//! fixture format ([`schema`]), discovers and loads vector files
//! ([`loader`]), and evaluates a loaded vector against the real `mtc` crate
//! types ([`runner`]), reporting a structural diff on mismatch rather than a
//! bare assertion failure. The vectors themselves live at
//! `conformance/vectors/` (repo root, sibling to `crates/`) — see that
//! directory's `README.md` for the format write-up and how to add a vector,
//! and `tests/conformance.rs` for the `#[test]` that discovers and runs every
//! one of them under plain `cargo test`.
//!
//! # Why this rides the existing CI gate
//!
//! `conformance/vectors/` is data, not code under `src/`; this crate is an
//! ordinary workspace member. `cargo test --workspace --all-features` (the
//! repository's `test` required check, spec §22.13) already builds and runs
//! every workspace crate's tests, so `tests/conformance.rs` running here is
//! automatically part of that required check — no separate CI job or branch
//! protection change is needed (spec §19.4 AC "Suite runs on every PR under
//! `cargo test --all-features`").
//!
//! # Clean-room vectors vs. draft vectors (scope note)
//!
//! The vectors seeded with this ticket are clean-room: their `wire_hex` bytes
//! come from this repository's own `mtc` serializers (`Checkpoint::sign` +
//! `serialize_tls_presentation`, `InclusionProof::generate` +
//! `tls_serialize_to_vec`, …), generated by `examples/generate_vectors.rs` and
//! locked as fixtures — never hand-invented byte layouts. Byte-exact
//! conformance against the `draft-ietf-plants-merkle-tree-certs-03` text
//! itself (vectors *authored from the draft*, proving this implementation
//! agrees with an independent source) is a separate, tracked obligation (bead
//! `mtc-qka.5`); this crate's vector format and runner are the harness that
//! will host those draft-derived vectors once they land — see the format
//! notes in `conformance/vectors/README.md` for what a draft-vector
//! contributor needs to match.
#![deny(missing_docs)]
#![warn(clippy::pedantic, clippy::nursery, clippy::cargo)]
#![cfg_attr(not(test), deny(clippy::unwrap_used, clippy::expect_used))]

pub mod hex;
pub mod loader;
pub mod runner;
pub mod schema;

pub use loader::{discover_vector_files, load_vector_file, LoadError};
pub use runner::evaluate;
pub use schema::Vector;
