//! `LocalStack`-backed conformance run of the shared `ObjectLock` suite
//! (ticket aws-backend Testing AC).
//!
//! Requires a running `LocalStack` container --
//! `docker compose -f deploy/local/docker-compose.yml up -d --wait
//! localstack` -- and the `integration` feature:
//! `cargo test -p cloud-aws --features integration`.

mod support;

use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use clock::{Clock, SystemClock};
use cloud_aws::S3ObjectStore;

/// Wraps [`SystemClock`], truncating to whole-second precision.
///
/// S3's `x-amz-object-lock-retain-until-date` (and the wire ISO 8601 value
/// `GetObjectRetention` returns) only carries second precision -- a real S3
/// platform characteristic, not a `LocalStack` shortcut. The suite's own
/// round-trip assertion (`put_with_retention` then `get_retention` returns
/// exactly what was sent) is only meaningful against a clock whose output
/// survives that precision loss unchanged; `SystemClock` alone would fail
/// the round trip on its sub-second component every run. See
/// `crates/cloud-aws/src/lib.rs` "Clock choice for the shared `ObjectLock`
/// suite".
struct SecondPrecisionClock(SystemClock);

impl Clock for SecondPrecisionClock {
    fn now(&self) -> SystemTime {
        let secs = self
            .0
            .now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or(Duration::ZERO)
            .as_secs();
        UNIX_EPOCH + Duration::from_secs(secs)
    }
}

#[tokio::test]
async fn s3_object_lock_passes_shared_conformance_suite() {
    let config = support::provision_test_bucket().await;
    // A real clock, not FakeClock: S3 evaluates retention windows against
    // its own real wall-clock time, so retain_until instants generated by
    // the suite (`clock.now() + Duration::from_hours(1)`) must be real,
    // future timestamps for S3's server-side enforcement to behave as the
    // suite expects -- see crates/cloud-aws/src/lib.rs "Clock choice for the
    // shared ObjectLock suite".
    let clock: Arc<dyn Clock> = Arc::new(SecondPrecisionClock(SystemClock));
    cloud_test_suite::run_object_lock_suite(|| async { S3ObjectStore::new(config.clone()) }, clock)
        .await;
}
