#!/usr/bin/env bash
# api-gen.sh — single regeneration entrypoint for the admin API (spec §17.2, §17.5).
#
# Pipeline:
#   1. Lint api/admin.openapi.yaml (Redocly CLI, pinned version below).
#   2. Generate the axum server-stub crate (rust-axum generator) and the Rust
#      client crate (rust generator, reqwest) into a scratch directory.
#   3. Post-process: drop tool boilerplate, stamp a @generated marker.
#   4. rsync --delete into crates/admin-api-server and crates/admin-api-client,
#      so the committed output is a pure function of the spec + pinned tools
#      (drift is detectable with `git diff`).
#   5. cargo fmt the generated crates with the repo-pinned toolchain so the
#      committed output is rustfmt-clean.
#
# Determinism: generator version is pinned in api/openapitools.json, Redocly in
# REDOCLY_VERSION, rustfmt via rust-toolchain.toml. Running this twice yields a
# byte-identical tree.
#
# The TypeScript client and HTML docs are generated by a separate pipeline
# (ticket fnd-openapi-ts-client-docs), not this script.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="$REPO_ROOT/api/admin.openapi.yaml"
REDOCLY_CONFIG="$REPO_ROOT/api/redocly.yaml"
OPENAPITOOLS_CONFIG="$REPO_ROOT/api/openapitools.json" # pins openapi-generator
REDOCLY_VERSION="2.40.0"

SERVER_DIR="$REPO_ROOT/crates/admin-api-server"
CLIENT_DIR="$REPO_ROOT/crates/admin-api-client"

LINT_ONLY=0
if [[ "${1:-}" == "--lint-only" ]]; then
  LINT_ONLY=1
fi

need() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'error: %s is required (%s)\n' "$1" "$2" >&2
    exit 1
  }
}
need npx "Node.js — runs the pinned Redocly + OpenAPI Generator CLIs"

# --- 1. Spec lint (spec §19.1: lint runs in the regen entrypoint) -----------
printf '==> Linting %s (redocly %s)\n' "${SPEC#"$REPO_ROOT"/}" "$REDOCLY_VERSION"
npx -y "@redocly/cli@${REDOCLY_VERSION}" lint --config "$REDOCLY_CONFIG"

if [[ "$LINT_ONLY" == 1 ]]; then
  exit 0
fi

need java "OpenAPI Generator is a JVM tool"
need rsync "syncs generated output into crates/"
need cargo "formats generated crates; install via rustup (https://rustup.rs)"

SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

generate() { # generate <generator-name> <out-dir> <additional-properties>
  npx -y @openapitools/openapi-generator-cli \
    --openapitools "$OPENAPITOOLS_CONFIG" \
    generate \
    -g "$1" \
    -i "$SPEC" \
    -o "$2" \
    --additional-properties="$3" \
    --global-property apiDocs=false,modelDocs=false,apiTests=false,modelTests=false \
    >"$SCRATCH/$1.log" 2>&1 || {
    printf 'error: openapi-generator (%s) failed; log follows\n' "$1" >&2
    cat "$SCRATCH/$1.log" >&2
    exit 1
  }
}

# --- 2. Generate server stubs + client into scratch -------------------------
printf '==> Generating axum server stubs (rust-axum)\n'
generate rust-axum "$SCRATCH/server" \
  "packageName=mtc-admin-api-server,packageVersion=0.1.0"

printf '==> Generating Rust client (rust/reqwest)\n'
generate rust "$SCRATCH/client" \
  "packageName=mtc-admin-api-client,packageVersion=0.1.0,library=reqwest,supportAsync=true,avoidBoxedModels=true"

# --- 3. Post-process --------------------------------------------------------
for dir in "$SCRATCH/server" "$SCRATCH/client"; do
  # Tool boilerplate that has no place inside a workspace member.
  rm -f "$dir/git_push.sh" "$dir/.travis.yml" "$dir/.gitignore"
  # The rust-axum README embeds a build timestamp (no generator option to
  # disable it); strip the line so regeneration is byte-identical.
  [[ -f "$dir/README.md" ]] && sed -i '/^- Build date: /d' "$dir/README.md"
  # Stamp Cargo.toml so nobody edits generated crates by hand.
  printf '# @generated by scripts/api-gen.sh — DO NOT EDIT.\n# Regenerate with `make api-gen` after editing api/admin.openapi.yaml (spec §17.5).\n%s' \
    "$(cat "$dir/Cargo.toml")" >"$dir/Cargo.toml.new"
  mv "$dir/Cargo.toml.new" "$dir/Cargo.toml"
  # Workspace members are never published (spec §1 non-goals); publish = false
  # also exempts these packages from clippy::cargo_common_metadata.
  sed -i '/^\[package\]/a publish = false' "$dir/Cargo.toml"
  # Generated code is exempt from the repo clippy regime: lint findings in it
  # are not actionable here (fix the generator or the spec instead), and CI
  # runs clippy with -D warnings (spec §22.13).
  cat >>"$dir/Cargo.toml" <<'EOF'

# Clippy exemption for generated code (see header). Allowed lints emit no
# diagnostics, so `cargo clippy -- -D warnings` stays green without editing
# generated sources.
[lints.clippy]
all = { level = "allow", priority = -1 }
pedantic = { level = "allow", priority = -1 }
nursery = { level = "allow", priority = -1 }
EOF
done

# --- 4. Sync into the workspace (delete stale files) ------------------------
printf '==> Syncing into %s and %s\n' "${SERVER_DIR#"$REPO_ROOT"/}" "${CLIENT_DIR#"$REPO_ROOT"/}"
mkdir -p "$SERVER_DIR" "$CLIENT_DIR"
rsync -a --delete "$SCRATCH/server/" "$SERVER_DIR/"
rsync -a --delete "$SCRATCH/client/" "$CLIENT_DIR/"

# --- 5. Format with the repo-pinned toolchain -------------------------------
printf '==> cargo fmt on generated crates\n'
(cd "$REPO_ROOT" && cargo fmt -p mtc-admin-api-server -p mtc-admin-api-client)

printf '==> Done. Review with: git status crates/admin-api-server crates/admin-api-client\n'
