//! Property tests for [`mtc_verify::verify_inclusion`] (spec §19.2, §19.8).
//!
//! Proofs generated by `mtc`'s own tree/proof modules for arbitrary trees verify
//! through the relying-party core, and any single-bit mutation of the entry, the
//! proof, or the committed root is rejected — never a panic.

// Integration-test helpers sit outside #[test] fns, so the allow-unwrap-in-tests
// exemption does not reach them (documented scoped-allow pattern,
// docs/lint-policy.md deviation 1).
#![allow(clippy::unwrap_used, clippy::expect_used)]

use mtc::{
    Checkpoint, CheckpointBuilder, Claim, DnsName, EcdsaP256, HashOutput, InclusionProof, Index,
    LogEntry, LogId, MerkleTree, Sha256Hasher, Signed, SignedAt, SigningKey, SubjectInfoHash,
    SubjectType, TbsCertificateLogEntry, TlsSerialize, TreeSize, VerifyingKey,
};
use mtc_verify::verify_inclusion;
use proptest::prelude::*;

type Tree = MerkleTree<Sha256Hasher>;

/// A certificate log entry whose subject-info hash is `hash` (so distinct hashes
/// give distinct entries and distinct leaf hashes).
fn entry_from(hash: [u8; 32]) -> LogEntry {
    LogEntry::certificate(
        TbsCertificateLogEntry::builder()
            .subject_type(SubjectType::Tls)
            .subject_info_hash(SubjectInfoHash::from_hash(HashOutput(hash)))
            .claim(Claim::dns(vec![DnsName::new(b"example.com".to_vec()).unwrap()]).unwrap())
            .build(),
    )
}

/// A distinct 32-byte subject hash for leaf `i`.
fn hash_for(i: u64) -> [u8; 32] {
    let mut h = [0u8; 32];
    h[..8].copy_from_slice(&i.to_le_bytes());
    h[8] = 0xA5;
    h
}

fn log_of(n: u64) -> (Vec<LogEntry>, Tree) {
    let entries: Vec<LogEntry> = (0..n).map(|i| entry_from(hash_for(i))).collect();
    let mut tree = Tree::new();
    for e in &entries {
        tree.append(&e.tls_serialize_to_vec().unwrap());
    }
    (entries, tree)
}

/// Signs a checkpoint over `root` at `size` and returns it with its CA key. The
/// signing key is returned too so tests can re-sign a mutated-root checkpoint.
fn sign_checkpoint(root: HashOutput, size: u64) -> (Checkpoint<Signed>, VerifyingKey, SigningKey) {
    let (signing, verifying) = EcdsaP256::generate_keypair();
    let cp = CheckpointBuilder::new(LogId::new("prop-log").unwrap())
        .root_hash(root)
        .tree_size(TreeSize(size))
        .signed_at(SignedAt(0))
        .build()
        .sign(&EcdsaP256, &signing)
        .unwrap();
    (cp, verifying, signing)
}

/// `seed`-derived byte index (0..32) and single-bit mask, for a one-bit flip of
/// a 32-byte hash.
fn flip_at(seed: u64) -> (usize, u8) {
    let byte = usize::try_from(seed % 32).unwrap();
    let mask = 1u8 << (seed / 32 % 8);
    (byte, mask)
}

proptest! {
    // Spec §19.2: for any tree size N and any leaf i < N, a proof generated by
    // `mtc` verifies through `verify_inclusion`.
    #[test]
    fn generated_proofs_verify(n in 1u64..80, seed in any::<u64>()) {
        let (entries, tree) = log_of(n);
        let (cp, pubkey, _sk) = sign_checkpoint(tree.root(), n);
        let i = seed % n;
        let iu = usize::try_from(i).unwrap();
        let proof = InclusionProof::generate(&tree, Index(i)).unwrap();
        let verified = verify_inclusion(&entries[iu], &proof, &cp, &pubkey)
            .expect("mtc-generated proof must verify");
        prop_assert_eq!(verified.leaf_index(), Index(i));
        prop_assert_eq!(verified.root_hash(), tree.root());
    }

    // Any single-bit mutation of the entry, the proof, or the committed root is
    // rejected — and never panics (spec §19.2, §19.8).
    #[test]
    fn single_bit_mutations_are_rejected(n in 2u64..80, seed in any::<u64>()) {
        let (entries, tree) = log_of(n);
        let (cp, pubkey, signing) = sign_checkpoint(tree.root(), n);
        let i = seed % n;
        let iu = usize::try_from(i).unwrap();
        let (byte, mask) = flip_at(seed);
        let proof = InclusionProof::generate(&tree, Index(i)).unwrap();

        // Baseline: the untampered triple verifies.
        prop_assert!(verify_inclusion(&entries[iu], &proof, &cp, &pubkey).is_ok());

        // (1) Mutate the entry: flip one bit of the subject-info hash.
        let mut mutated = hash_for(i);
        mutated[byte] ^= mask;
        let mutated_entry = entry_from(mutated);
        prop_assert!(
            verify_inclusion(&mutated_entry, &proof, &cp, &pubkey).is_err(),
            "mutated entry must be rejected",
        );

        // (2) Mutate the proof: flip one bit of a random audit-path element.
        if !proof.audit_path().is_empty() {
            let mut path = proof.audit_path().to_vec();
            let pos = usize::try_from(seed % (path.len() as u64)).unwrap();
            path[pos].0[byte] ^= mask;
            let tampered = InclusionProof::from_parts(proof.tree_size(), proof.leaf_index(), path);
            prop_assert!(
                verify_inclusion(&entries[iu], &tampered, &cp, &pubkey).is_err(),
                "tampered proof must be rejected",
            );
        }

        // (3) Mutate the committed root: flip one bit, re-sign so the signature
        // is valid over the (wrong) root. The proof cannot reconstruct it.
        let mut wrong_root = tree.root().to_bytes();
        wrong_root[byte] ^= mask;
        let cp_wrong = CheckpointBuilder::new(LogId::new("prop-log").unwrap())
            .root_hash(HashOutput(wrong_root))
            .tree_size(TreeSize(n))
            .signed_at(SignedAt(0))
            .build()
            .sign(&EcdsaP256, &signing)
            .unwrap();
        prop_assert!(
            verify_inclusion(&entries[iu], &proof, &cp_wrong, &pubkey).is_err(),
            "proof against a mutated root must be rejected",
        );
    }

    // Spec §19.8: arbitrary audit-path bytes and indices never panic — the
    // verifier always returns Ok or a typed VerifyError.
    #[test]
    fn arbitrary_proof_shapes_never_panic(
        n in 1u64..40,
        seed in any::<u64>(),
        extra in prop::collection::vec(any::<[u8; 32]>(), 0..40),
        declared_index in any::<u64>(),
    ) {
        let (entries, tree) = log_of(n);
        let (cp, pubkey, _sk) = sign_checkpoint(tree.root(), n);
        let path: Vec<HashOutput> = extra.into_iter().map(HashOutput).collect();
        let arbitrary = InclusionProof::from_parts(TreeSize(n), Index(declared_index), path);
        let iu = usize::try_from(seed % n).unwrap();
        // Must return, never panic.
        let _ = verify_inclusion(&entries[iu], &arbitrary, &cp, &pubkey);
    }
}
